class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'manage_brands': 'Manage Brands',
      'app_title': 'Car Collector',
      'welcome': 'Welcome',
      'enter_name': 'Enter your username to begin your garage collection:',
      'username': 'Username',
      'start_collecting': 'Start Collecting',
      'home': 'Home',
      'collection': 'Collection',
      'brands': 'Brands',
      'profile': 'Profile',
      'cars_collected': 'Cars Collected',
      'brands_added': 'Brands Added',
      'total_hp': 'Total Horsepower',
      'top_brand': 'Top Brand',
      'recent_cars': 'Recently Added Cars',
      'add_car': 'Add Car',
      'quick_add_brand': 'Quick Add',
      'collection_progress': 'Collection Progress',
      'search_placeholder': 'Search cars or brands...',
      'filter': 'Filter',
      'sort_by': 'Sort By',
      'newest': 'Newest',
      'oldest': 'Oldest',
      'hp_desc': 'Horsepower (High to Low)',
      'price_desc': 'Price (High to Low)',
      'name_asc': 'Name (A-Z)',
      'empty_collection': 'Your garage is currently empty!',
      'start_first_car': 'Add your very first car to unlock achievements.',
      'add_first_car': 'Add Your First Car',
      'no_brands': 'No brands added yet.',
      'add_brand': 'Add Brand',
      'car_details': 'Car Details',
      'specifications': 'Specifications',
      'engine': 'Engine Capacity',
      'cylinders': 'Cylinders',
      'horsepower': 'Horsepower',
      'transmission': 'Transmission',
      'year': 'Production Year',
      'category': 'Category',
      'zero_to_hundred': '0-100 km/h',
      'price_egp': 'Price (EGP)',
      'price_usd': 'Price (USD)',
      'gallery': 'Car Gallery (5 Photos Required)',
      'edit': 'Edit',
      'delete_car': 'Delete Car',
      'delete_confirm':
          'Are you sure you want to delete this car from your collection?',
      'delete_brand_confirm':
          'Deleting this brand will affect all cars linked to it. Continue?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'save': 'Save Car',
      'save_changes': 'Save Changes',
      'car_name': 'Car Name',
      'manual': 'Manual',
      'edit_car': 'Edit Car',
      'automatic': 'Automatic',
      'camera_soon': 'Camera (Coming Soon)',
      'select_5_images': 'Please select exactly 5 images of the car.',
      'car_saved': 'Car successfully added to your collection!',
      'car_updated': 'Car updated successfully!',
      'brand_name': 'Brand Name',
      'edit_brand': 'Edit Brand',
      'theme': 'Theme',
      'dark': 'Dark',
      'light': 'Light',
      'system': 'System',
      'profile_image': 'Profile Image',
      'language': 'Language',
      'english': 'English',
      'arabic': 'العربية',
      'level_new': 'New Collector',
      'level_hunter': 'Car Hunter',
      'level_builder': 'Garage Builder',
      'level_fleet': 'Fleet Collector',
      'level_collector': 'Car Collector',
      'level_elite': 'Elite Collector',
      'edit_profile': 'Edit Username',
      'fill_required': 'Please fill all required fields correctly.',
      'image': 'Image',
      'active': 'Active',
      'cars': 'Cars',
      'all_vehicles': 'All Vehicles',
      'add_first_brand': 'Add Your First Brand',
      'quick_add': 'Quick Add',
      'preselections': '1. Preselections',
      'car_specs': '2. Car Specifications',
      'photo_gallery': '3. Photo Gallery',
      'add': 'Add',
      'add_image': 'Add Image',
      'main_image': 'Main',
      'must_add_5_images': 'Must add exactly 5 images',
      'capture_photo': 'Capture Photo',
      'choose_from_gallery': 'Choose from Gallery',
      'delete_image': 'Delete Image',
      'select_image_source': 'Select Image Source',
      'permissions_required': 'Permissions Required',
      'grant_permission': 'Please grant permission for',
      'from_device_settings': 'from device settings',
      'settings': 'Settings',
      'camera': 'Camera',
      'photos_access': 'Photos Access',
      'storage_access': 'Storage Access',
      'insufficient_permissions': 'Insufficient permissions',
      'no_image_selected': 'No image selected',
      'image_too_large':
          'Image too large. Please select an image less than 10 MB.',
      'image_too_large_5mb': 'Image too large. Maximum 5 MB.',
      'image_selected': 'Image selected successfully',
      'error_picking_image': 'Error picking image',
      'error_saving_car': 'Error saving car',
      'error_updating_car': 'Error updating car',
      'error': 'Error',
      'select_brand_image': 'Select Brand Image',
      'tap_to_add_image': 'Tap to add image (optional)',
      'tap_to_change_image': 'Tap to change image',
      'delete_brand': 'Delete Brand',
      'no_cars_for_brand': 'No cars for this brand',
      'no_matching_results': 'No matching results',
      'add_first_car_for_brand': 'Add your first car for this brand',
      'try_different_search': 'Try searching with different keywords',
      'hp': 'HP',
      'broken_image': 'Broken Image',
      'image_required': 'Brand image is required',
      'brand_name_required': 'Brand name is required',
    },
    'ar': {
      'manage_brands': 'إدارة العلامات التجارية',
      'app_title': 'جامع السيارات',
      'welcome': 'أهلاً بك',
      'enter_name': 'أدخل اسم المستخدم للبدء في بناء كراج أحلامك:',
      'username': 'اسم المستخدم',
      'start_collecting': 'ابدأ التجميع',
      'home': 'الرئيسية',
      'collection': 'المجموعة',
      'brands': 'العلامات التجارية',
      'profile': 'الملف الشخصي',
      'cars_collected': 'السيارات المجمعة',
      'brands_added': 'العلامات المضافة',
      'total_hp': 'إجمالي القوة الحصانية',
      'top_brand': 'العلامة الأكثر تجميعاً',
      'recent_cars': 'آخر السيارات المضافة',
      'add_car': 'إضافة سيارة',
      'quick_add_brand': 'إضافة سريعة',
      'collection_progress': 'تقدم التجميع',
      'search_placeholder': 'ابحث باسم السيارة أو العلامة التجارية...',
      'filter': 'تصفية',
      'sort_by': 'ترتيب حسب',
      'newest': 'الأحدث',
      'oldest': 'الأقدم',
      'hp_desc': 'القوة الحصانية (الأعلى أولاً)',
      'price_desc': 'السعر (الأعلى أولاً)',
      'name_asc': 'الاسم (أبجدياً)',
      'empty_collection': 'مكتبة سياراتك فارغة حالياً!',
      'start_first_car': 'أضف سيارتك الأولى للبدء في رفع مستواك.',
      'add_first_car': 'أضف سيارتك الأولى',
      'no_brands': 'لم يتم إضافة أي علامة تجارية بعد.',
      'add_brand': 'إضافة علامة تجارية',
      'car_details': 'تفاصيل السيارة',
      'specifications': 'المواصفات الفنية',
      'engine': 'سعة المحرك',
      'cylinders': 'عدد الأسطوانات',
      'horsepower': 'القوة الحصانية',
      'transmission': 'ناقل الحركة',
      'year': 'سنة الصنع',
      'category': 'فئة السيارة',
      'zero_to_hundred': '0-100 كم/س',
      'profile_image': 'صورة الملف الشخصي',
      'price_egp': 'السعر بالجنيه المصري',
      'price_usd': 'السعر بالدولار الأمريكي',
      'gallery': 'معرض الصور (مطلوب 5 صور بالضبط)',
      'edit': 'تعديل',
      'delete_car': 'حذف السيارة',
      'delete_confirm': 'هل أنت متأكد من رغبتك في حذف هذه السيارة من مجموعتك؟',
      'delete_brand_confirm':
          'حذف هذه العلامة قد يؤثر على السيارات المرتبطة بها. هل تريد المتابعة؟',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'save': 'حفظ السيارة',
      'save_changes': 'حفظ التغييرات',
      'car_name': 'اسم السيارة',
      'manual': 'يدوي',
      'edit_car': 'تعديل السيارة',
      'automatic': 'أوتوماتيك',
      'camera_soon': 'الكاميرا (قريباً)',
      'select_5_images': 'يرجى اختيار 5 صور بالضبط للسيارة.',
      'car_saved': 'تمت إضافة السيارة إلى مجموعتك بنجاح!',
      'car_updated': 'تم تحديث بيانات السيارة بنجاح!',
      'brand_name': 'اسم العلامة التجارية',
      'edit_brand': 'تعديل العلامة',
      'theme': 'المظهر',
      'dark': 'داكن',
      'light': 'فاتح',
      'system': 'النظام',
      'language': 'اللغة',
      'english': 'English',
      'arabic': 'العربية',
      'level_new': 'جامع مبتدئ',
      'level_hunter': 'صائد السيارات',
      'level_builder': 'بناء الكراج',
      'level_fleet': 'جامع الأساطيل',
      'level_collector': 'خبير السيارات',
      'level_elite': 'جامع النخبة',
      'edit_profile': 'تعديل اسم المستخدم',
      'fill_required': 'يرجى ملء جميع الحقول المطلوبة بشكل صحيح.',
      'image': 'صورة',
      'active': 'نشط',
      'cars': 'سيارة',
      'all_vehicles': 'جميع المركبات',
      'add_first_brand': 'أضف علامتك التجارية الأولى',
      'quick_add': 'إضافة سريعة',
      'preselections': '1. الاختيارات المسبقة',
      'car_specs': '2. مواصفات السيارة',
      'photo_gallery': '3. معرض الصور',
      'add': 'إضافة',
      'add_image': 'إضافة صورة',
      'main_image': 'رئيسية',
      'must_add_5_images': 'يجب إضافة 5 صور بالضبط',
      'capture_photo': 'التقاط صورة',
      'choose_from_gallery': 'اختيار من المعرض',
      'delete_image': 'حذف الصورة',
      'select_image_source': 'اختر مصدر الصورة',
      'permissions_required': 'الأذونات مطلوبة',
      'grant_permission': 'يرجى منح إذن',
      'from_device_settings': 'من إعدادات الجهاز',
      'settings': 'الإعدادات',
      'camera': 'الكاميرا',
      'photos_access': 'الوصول إلى الصور',
      'storage_access': 'الوصول إلى التخزين',
      'insufficient_permissions': 'لا توجد أذونات كافية',
      'no_image_selected': 'لم يتم اختيار أي صورة',
      'image_too_large':
          'الصورة كبيرة جداً. الرجاء اختيار صورة أقل من 10 ميجابايت.',
      'image_too_large_5mb': 'الصورة كبيرة جداً. الحد الأقصى 5 ميجابايت.',
      'image_selected': 'تم اختيار الصورة بنجاح',
      'error_picking_image': 'حدث خطأ في اختيار الصورة',
      'error_saving_car': 'حدث خطأ في حفظ السيارة',
      'error_updating_car': 'حدث خطأ في تحديث السيارة',
      'error': 'خطأ',
      'select_brand_image': 'اختر صورة العلامة',
      'tap_to_add_image': 'اضغط لإضافة صورة (اختياري)',
      'tap_to_change_image': 'اضغط لتغيير الصورة',
      'delete_brand': 'حذف العلامة التجارية',
      'no_cars_for_brand': 'لا توجد سيارات لهذه العلامة',
      'no_matching_results': 'لا توجد نتائج مطابقة',
      'add_first_car_for_brand': 'أضف سيارتك الأولى من هذه العلامة',
      'try_different_search': 'جرب البحث بكلمات مختلفة',
      'hp': 'حصان',
      'broken_image': 'صورة تالفة',
      'image_required': 'صورة البراند مطلوبة',
      'brand_name_required': 'اسم البراند مطلوب',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
